# Generated by Django 4.2.16 on 2024-11-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityPlanning', "0002_project_message_uploadedfile_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
