# Generated by Django 4.2.16 on 2024-12-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityPlanning', '0004_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='votes',
        ),
        migrations.AddField(
            model_name='project',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
