# Generated by Django 4.2.16 on 2024-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityPlanning', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='hacky_sol',
            field=models.IntegerField(default=0),
        ),
    ]
