# Generated by Django 4.2.16 on 2025-02-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cityPlanning", "0010_project_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="cityPlanning.project",
            ),
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
