# Generated by Django 4.2.16 on 2025-02-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cityPlanning", "0011_alter_message_project_delete_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.JSONField(default=dict),
        ),
    ]
